name: "NextDNS CLI"
description: "NextDNS CLI DNS resolver for HAOS"
version: "1.0.0"
slug: nextdns_cli
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
map:
  - config:rw
ports:
  53/tcp: null
  53/udp: null
mode: host_network
options:
  profile_id: "da8163"
  listen: ":53"
schema:
  profile_id: "str"
  listen: "str?"
